-- Seed Daily Sparks Data
insert into public.daily_sparks (content, author, date) values
('No necesitas más tiempo, necesitas más foco. Decidir es renunciar.', 'Rompe el Ciclo', CURRENT_DATE),
('Tu primera versión va a ser mala. Ese es el precio de entrada.', 'Rompe el Ciclo', CURRENT_DATE + 1),
('El miedo no se va, se atraviesa. Si esperas a no tenerlo, morirás esperando.', 'Rompe el Ciclo', CURRENT_DATE + 2),
('La preparación infinita es el escondite favorito de los cobardes.', 'Rompe el Ciclo', CURRENT_DATE + 3),
('Tu entorno es tu destino. Si tus amigos son mediocres, tú eres el quinto.', 'Rompe el Ciclo', CURRENT_DATE + 4),
('Vender es servir. Si tienes la cura y no la vendes, eres un egoísta.', 'Rompe el Ciclo', CURRENT_DATE + 5),
('La motivación es para los amateurs. Los profesionales se basan en sistemas.', 'Rompe el Ciclo', CURRENT_DATE + 6),
('A nadie le importa tu potencial, solo tus resultados.', 'Rompe el Ciclo', CURRENT_DATE + 7),
('El "no" ya lo tienes. Solo estás peleando por el "sí".', 'Rompe el Ciclo', CURRENT_DATE + 8),
('Dormir más de la cuenta no es descanso, es escape.', 'Rompe el Ciclo', CURRENT_DATE + 9),
('Tu cerebro es un experto en mentirte para mantenerte a salvo.', 'Rompe el Ciclo', CURRENT_DATE + 10),
('La claridad viene de la acción, no de la reflexión.', 'Rompe el Ciclo', CURRENT_DATE + 11),
('O controlas tu agenda o alguien más lo hará por ti.', 'Rompe el Ciclo', CURRENT_DATE + 12),
('El perfeccionismo es procrastinación con traje elegante.', 'Rompe el Ciclo', CURRENT_DATE + 13),
('Si no estás cansado al final del día, no estás viviendo, estás durmiendo despierto.', 'Rompe el Ciclo', CURRENT_DATE + 14),
('Pedir perdón por cobrar es insultar tu propio valor.', 'Rompe el Ciclo', CURRENT_DATE + 15),
('La disciplina es recordarte lo que quieres cuando el ánimo se va.', 'Rompe el Ciclo', CURRENT_DATE + 16),
('Tu pasado no es una cadena, es una lección pagada.', 'Rompe el Ciclo', CURRENT_DATE + 17),
('La mayoría de los problemas se resuelven con más ingresos.', 'Rompe el Ciclo', CURRENT_DATE + 18),
('Quejarse es para las víctimas. Los operadores buscan soluciones.', 'Rompe el Ciclo', CURRENT_DATE + 19),
('La consistencia vence al talento el 100% de las veces.', 'Rompe el Ciclo', CURRENT_DATE + 20),
('El éxito es aburrido. Es repetir lo básico mil veces.', 'Rompe el Ciclo', CURRENT_DATE + 21),
('No busques aprobación de gente que no ha construido nada.', 'Rompe el Ciclo', CURRENT_DATE + 22),
('Tu cuerpo es el motor de tu negocio. No lo ignores.', 'Rompe el Ciclo', CURRENT_DATE + 23),
('Mañana es la palabra favorita de los perdedores.', 'Rompe el Ciclo', CURRENT_DATE + 24),
('La vulnerabilidad es poder. Sé real, no perfecto.', 'Rompe el Ciclo', CURRENT_DATE + 25),
('Si no mides, no controlas. Si no controlas, no escalas.', 'Rompe el Ciclo', CURRENT_DATE + 26),
('El cansancio es mental el 90% del tiempo.', 'Rompe el Ciclo', CURRENT_DATE + 27),
('La suerte es lo que pasa cuando la preparación encuentra la oportunidad.', 'Rompe el Ciclo', CURRENT_DATE + 28),
('Has completado 30 días. El ciclo se está rompiendo. No te detengas.', 'Rompe el Ciclo', CURRENT_DATE + 29);
