-- Create Pillars Table
create table if not exists public.pillars (
  id bigint generated by default as identity primary key,
  titulo text not null,
  subtitulo text not null,
  concepto text not null,
  accion text not null,
  ejercicio text not null,
  is_locked_by_default boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.pillars enable row level security;

-- Create Policy (Read Only for Authenticated)
create policy "Pillars are viewable by everyone" on public.pillars for select using (true);

-- Create Daily Sparks Table
create table if not exists public.daily_sparks (
  id bigint generated by default as identity primary key,
  content text not null,
  author text,
  date date default CURRENT_DATE,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.daily_sparks enable row level security;

-- Create Policy
create policy "Sparks are viewable by everyone" on public.daily_sparks for select using (true);

-- Seed Data (Initial Pillars from App.tsx)
insert into public.pillars (id, titulo, subtitulo, concepto, accion, ejercicio, is_locked_by_default) values
(0, 'EL DESPERTAR', 'Protocolo de Consciencia', 'Tu vida es una repetición. Romper el ciclo requiere dolor.', 'Análisis de Patrones', 'El Muro de la Verdad', false),
(1, 'TRAMPA MENTAL', 'Procrastinación Culta', 'Estudiar es un escondite. La teoría sin práctica es veneno.', 'Dieta de Información', 'Confesión del Espejo', true),
(2, 'VERDAD DEL MIEDO', 'Riesgo Emocional', 'Decidir con miedo es la única forma de crecer.', 'Regla 30 días.', 'Botón del Pánico Inverso', true),
(3, 'VENDER ES AMAR', 'Tu Valor Real', 'No vender es egoísmo puro.', 'Lanzamiento Flash.', 'Generador de Oferta Flash', true),
(4, 'MOTOR DE ACCIÓN', 'Sistemas sobre Emociones', 'El impulso vence a la motivación.', 'Acción Mínima Diaria.', 'Streak Tracker', true),
(5, 'CÍRCULO DE FUEGO', 'Gestión del Entorno', 'Tu fuerza de voluntad no puede contra tu entorno.', 'Auditoría Social', 'Lista de Despido', true),
(6, 'EL FRACASO ES DATO', 'Resiliencia Kaizen', 'Quítale la emoción al error. Solo es información.', 'Re-encuadre Táctico', 'Post-Mortem de Éxito', true)
ON CONFLICT (id) DO NOTHING;
